import 'package:flutter/material.dart';
import '../theme_manager.dart';

/// Color palettes for all 6 themes — light and dark variants.
abstract final class AppColors {
  // ── Theme 1: Healthcare Classic ─────────────────────────────────────────────
  static const ColorScheme healthcareClassicLight = ColorScheme(
    brightness:           Brightness.light,
    primary:              Color(0xFF006A60),
    onPrimary:            Color(0xFFFFFFFF),
    primaryContainer:     Color(0xFF9EF2E4),
    onPrimaryContainer:   Color(0xFF00201C),
    secondary:            Color(0xFF2B6359),
    onSecondary:          Color(0xFFFFFFFF),
    secondaryContainer:   Color(0xFFAEEBDD),
    onSecondaryContainer: Color(0xFF00201A),
    tertiary:             Color(0xFF4B6546),
    onTertiary:           Color(0xFFFFFFFF),
    tertiaryContainer:    Color(0xFFCCEBC4),
    onTertiaryContainer:  Color(0xFF082009),
    error:                Color(0xFFBA1A1A),
    onError:              Color(0xFFFFFFFF),
    errorContainer:       Color(0xFFFFDAD6),
    onErrorContainer:     Color(0xFF410002),
    surface:              Color(0xFFFFFFFF),
    onSurface:            Color(0xFF001F1C),
    surfaceContainerHighest: Color(0xFFDAE5E2),
    onSurfaceVariant:     Color(0xFF3F4947),
    outline:              Color(0xFF6F7976),
    outlineVariant:       Color(0xFFBEC9C6),
    shadow:               Color(0xFF000000),
    scrim:                Color(0xFF000000),
    inverseSurface:       Color(0xFF2A3431),
    onInverseSurface:     Color(0xFFECF2F0),
    inversePrimary:       Color(0xFF82D5C8),
  );

  static const ColorScheme healthcareClassicDark = ColorScheme(
    brightness:           Brightness.dark,
    primary:              Color(0xFF82D5C8),
    onPrimary:            Color(0xFF003731),
    primaryContainer:     Color(0xFF005047),
    onPrimaryContainer:   Color(0xFF9EF2E4),
    secondary:            Color(0xFF92CEC2),
    onSecondary:          Color(0xFF003731),
    secondaryContainer:   Color(0xFF004941),
    onSecondaryContainer: Color(0xFFAEEBDD),
    tertiary:             Color(0xFFB0CFAA),
    onTertiary:           Color(0xFF1D361C),
    tertiaryContainer:    Color(0xFF334D31),
    onTertiaryContainer:  Color(0xFFCCEBC4),
    error:                Color(0xFFFFB4AB),
    onError:              Color(0xFF690005),
    errorContainer:       Color(0xFF93000A),
    onErrorContainer:     Color(0xFFFFDAD6),
    surface:              Color(0xFF0E1413),
    onSurface:            Color(0xFFDCE4E2),
    surfaceContainerHighest: Color(0xFF3F4947),
    onSurfaceVariant:     Color(0xFFBEC9C6),
    outline:              Color(0xFF899390),
    outlineVariant:       Color(0xFF3F4947),
    shadow:               Color(0xFF000000),
    scrim:                Color(0xFF000000),
    inverseSurface:       Color(0xFFDCE4E2),
    onInverseSurface:     Color(0xFF2A3431),
    inversePrimary:       Color(0xFF006A60),
  );

  // ── Theme 2: Modern Blue ────────────────────────────────────────────────────
  static const ColorScheme modernBlueLight = ColorScheme(
    brightness:           Brightness.light,
    primary:              Color(0xFF1855BF),
    onPrimary:            Color(0xFFFFFFFF),
    primaryContainer:     Color(0xFFDAE2FF),
    onPrimaryContainer:   Color(0xFF001452),
    secondary:            Color(0xFF3949AB),
    onSecondary:          Color(0xFFFFFFFF),
    secondaryContainer:   Color(0xFFE0E3FF),
    onSecondaryContainer: Color(0xFF000B6A),
    tertiary:             Color(0xFF0277BD),
    onTertiary:           Color(0xFFFFFFFF),
    tertiaryContainer:    Color(0xFFCDE5FF),
    onTertiaryContainer:  Color(0xFF001E35),
    error:                Color(0xFFBA1A1A),
    onError:              Color(0xFFFFFFFF),
    errorContainer:       Color(0xFFFFDAD6),
    onErrorContainer:     Color(0xFF410002),
    surface:              Color(0xFFFFFFFF),
    onSurface:            Color(0xFF1A1B22),
    surfaceContainerHighest: Color(0xFFE1E3F3),
    onSurfaceVariant:     Color(0xFF44475C),
    outline:              Color(0xFF74778A),
    outlineVariant:       Color(0xFFC4C6D9),
    shadow:               Color(0xFF000000),
    scrim:                Color(0xFF000000),
    inverseSurface:       Color(0xFF2F3038),
    onInverseSurface:     Color(0xFFF1F0F8),
    inversePrimary:       Color(0xFFB4C4FF),
  );

  static const ColorScheme modernBlueDark = ColorScheme(
    brightness:           Brightness.dark,
    primary:              Color(0xFFB4C4FF),
    onPrimary:            Color(0xFF002585),
    primaryContainer:     Color(0xFF003DAD),
    onPrimaryContainer:   Color(0xFFDAE2FF),
    secondary:            Color(0xFFBEC3FF),
    onSecondary:          Color(0xFF0A0E78),
    secondaryContainer:   Color(0xFF2230A0),
    onSecondaryContainer: Color(0xFFE0E3FF),
    tertiary:             Color(0xFF92CCFF),
    onTertiary:           Color(0xFF003258),
    tertiaryContainer:    Color(0xFF004B83),
    onTertiaryContainer:  Color(0xFFCDE5FF),
    error:                Color(0xFFFFB4AB),
    onError:              Color(0xFF690005),
    errorContainer:       Color(0xFF93000A),
    onErrorContainer:     Color(0xFFFFDAD6),
    surface:              Color(0xFF12131A),
    onSurface:            Color(0xFFE2E2EC),
    surfaceContainerHighest: Color(0xFF44475C),
    onSurfaceVariant:     Color(0xFFC4C6D9),
    outline:              Color(0xFF8E90A4),
    outlineVariant:       Color(0xFF44475C),
    shadow:               Color(0xFF000000),
    scrim:                Color(0xFF000000),
    inverseSurface:       Color(0xFFE2E2EC),
    onInverseSurface:     Color(0xFF2F3038),
    inversePrimary:       Color(0xFF1855BF),
  );

  // ── Theme 3: Wellness Green ─────────────────────────────────────────────────
  static const ColorScheme wellnessGreenLight = ColorScheme(
    brightness:           Brightness.light,
    primary:              Color(0xFF2E6B33),
    onPrimary:            Color(0xFFFFFFFF),
    primaryContainer:     Color(0xFFB2EBB7),
    onPrimaryContainer:   Color(0xFF002109),
    secondary:            Color(0xFF4A7A23),
    onSecondary:          Color(0xFFFFFFFF),
    secondaryContainer:   Color(0xFFCAF09A),
    onSecondaryContainer: Color(0xFF0F2100),
    tertiary:             Color(0xFF00838F),
    onTertiary:           Color(0xFFFFFFFF),
    tertiaryContainer:    Color(0xFFB2EBF2),
    onTertiaryContainer:  Color(0xFF00201F),
    error:                Color(0xFFBA1A1A),
    onError:              Color(0xFFFFFFFF),
    errorContainer:       Color(0xFFFFDAD6),
    onErrorContainer:     Color(0xFF410002),
    surface:              Color(0xFFFAFFF5),
    onSurface:            Color(0xFF001F07),
    surfaceContainerHighest: Color(0xFFD8E8D8),
    onSurfaceVariant:     Color(0xFF3C4840),
    outline:              Color(0xFF6C786F),
    outlineVariant:       Color(0xFFBCCBBE),
    shadow:               Color(0xFF000000),
    scrim:                Color(0xFF000000),
    inverseSurface:       Color(0xFF293029),
    onInverseSurface:     Color(0xFFECF3EC),
    inversePrimary:       Color(0xFF97D79C),
  );

  static const ColorScheme wellnessGreenDark = ColorScheme(
    brightness:           Brightness.dark,
    primary:              Color(0xFF97D79C),
    onPrimary:            Color(0xFF003912),
    primaryContainer:     Color(0xFF155221),
    onPrimaryContainer:   Color(0xFFB2EBB7),
    secondary:            Color(0xFFAED582),
    onSecondary:          Color(0xFF1C3901),
    secondaryContainer:   Color(0xFF31520C),
    onSecondaryContainer: Color(0xFFCAF09A),
    tertiary:             Color(0xFF80DEEA),
    onTertiary:           Color(0xFF003B43),
    tertiaryContainer:    Color(0xFF005762),
    onTertiaryContainer:  Color(0xFFB2EBF2),
    error:                Color(0xFFFFB4AB),
    onError:              Color(0xFF690005),
    errorContainer:       Color(0xFF93000A),
    onErrorContainer:     Color(0xFFFFDAD6),
    surface:              Color(0xFF0E150F),
    onSurface:            Color(0xFFDEE5DC),
    surfaceContainerHighest: Color(0xFF3C4840),
    onSurfaceVariant:     Color(0xFFBCCBBE),
    outline:              Color(0xFF86938A),
    outlineVariant:       Color(0xFF3C4840),
    shadow:               Color(0xFF000000),
    scrim:                Color(0xFF000000),
    inverseSurface:       Color(0xFFDEE5DC),
    onInverseSurface:     Color(0xFF293029),
    inversePrimary:       Color(0xFF2E6B33),
  );

  // ── Theme 4: Professional Dark ──────────────────────────────────────────────
  // Both light and dark are dark — this is an OLED-optimised dark theme.
  static const ColorScheme professionalDark = ColorScheme(
    brightness:           Brightness.dark,
    primary:              Color(0xFF80CBC4),
    onPrimary:            Color(0xFF003731),
    primaryContainer:     Color(0xFF00504A),
    onPrimaryContainer:   Color(0xFF9EF2E8),
    secondary:            Color(0xFF80DEEA),
    onSecondary:          Color(0xFF00363E),
    secondaryContainer:   Color(0xFF004F58),
    onSecondaryContainer: Color(0xFFB2EBF2),
    tertiary:             Color(0xFF82B1FF),
    onTertiary:           Color(0xFF002370),
    tertiaryContainer:    Color(0xFF00359C),
    onTertiaryContainer:  Color(0xFFDAE2FF),
    error:                Color(0xFFFF5252),
    onError:              Color(0xFF690005),
    errorContainer:       Color(0xFF93000A),
    onErrorContainer:     Color(0xFFFFDAD6),
    surface:              Color(0xFF050A0E),
    onSurface:            Color(0xFFE3EAF0),
    surfaceContainerHighest: Color(0xFF151B23),
    onSurfaceVariant:     Color(0xFFB8C4CC),
    outline:              Color(0xFF405060),
    outlineVariant:       Color(0xFF222D38),
    shadow:               Color(0xFF000000),
    scrim:                Color(0xFF000000),
    inverseSurface:       Color(0xFFE3EAF0),
    onInverseSurface:     Color(0xFF0D1820),
    inversePrimary:       Color(0xFF006A60),
  );

  // ── Theme 5: Accessibility ──────────────────────────────────────────────────
  static const ColorScheme accessibilityLight = ColorScheme(
    brightness:           Brightness.light,
    primary:              Color(0xFF000000),
    onPrimary:            Color(0xFFFFFFFF),
    primaryContainer:     Color(0xFF1A1A1A),
    onPrimaryContainer:   Color(0xFFFFFFFF),
    secondary:            Color(0xFF0000CC),
    onSecondary:          Color(0xFFFFFFFF),
    secondaryContainer:   Color(0xFFDDE0FF),
    onSecondaryContainer: Color(0xFF00007A),
    tertiary:             Color(0xFF006600),
    onTertiary:           Color(0xFFFFFFFF),
    tertiaryContainer:    Color(0xFFCCFFCC),
    onTertiaryContainer:  Color(0xFF004400),
    error:                Color(0xFFCC0000),
    onError:              Color(0xFFFFFFFF),
    errorContainer:       Color(0xFFFFE5E5),
    onErrorContainer:     Color(0xFF880000),
    surface:              Color(0xFFFFFFFF),
    onSurface:            Color(0xFF000000),
    surfaceContainerHighest: Color(0xFFEEEEEE),
    onSurfaceVariant:     Color(0xFF000000),
    outline:              Color(0xFF000000),
    outlineVariant:       Color(0xFF666666),
    shadow:               Color(0xFF000000),
    scrim:                Color(0xFF000000),
    inverseSurface:       Color(0xFF000000),
    onInverseSurface:     Color(0xFFFFFFFF),
    inversePrimary:       Color(0xFFFFFFFF),
  );

  static const ColorScheme accessibilityDark = ColorScheme(
    brightness:           Brightness.dark,
    primary:              Color(0xFFFFFFFF),
    onPrimary:            Color(0xFF000000),
    primaryContainer:     Color(0xFFDDDDDD),
    onPrimaryContainer:   Color(0xFF000000),
    secondary:            Color(0xFF99CCFF),
    onSecondary:          Color(0xFF000033),
    secondaryContainer:   Color(0xFF003399),
    onSecondaryContainer: Color(0xFFCCE5FF),
    tertiary:             Color(0xFF99FF99),
    onTertiary:           Color(0xFF003300),
    tertiaryContainer:    Color(0xFF006600),
    onTertiaryContainer:  Color(0xFFCCFFCC),
    error:                Color(0xFFFF6666),
    onError:              Color(0xFF000000),
    errorContainer:       Color(0xFF880000),
    onErrorContainer:     Color(0xFFFFCCCC),
    surface:              Color(0xFF000000),
    onSurface:            Color(0xFFFFFFFF),
    surfaceContainerHighest: Color(0xFF1A1A1A),
    onSurfaceVariant:     Color(0xFFFFFFFF),
    outline:              Color(0xFFFFFFFF),
    outlineVariant:       Color(0xFFAAAAAA),
    shadow:               Color(0xFF000000),
    scrim:                Color(0xFF000000),
    inverseSurface:       Color(0xFFFFFFFF),
    onInverseSurface:     Color(0xFF000000),
    inversePrimary:       Color(0xFF000000),
  );

  // ── Theme 6: Australian Clinical ────────────────────────────────────────────
  static const ColorScheme australianClinicalLight = ColorScheme(
    brightness:           Brightness.light,
    primary:              Color(0xFF00695C),
    onPrimary:            Color(0xFFFFFFFF),
    primaryContainer:     Color(0xFFCCECE7),
    onPrimaryContainer:   Color(0xFF002922),
    secondary:            Color(0xFFE65100),
    onSecondary:          Color(0xFFFFFFFF),
    secondaryContainer:   Color(0xFFFFCCBC),
    onSecondaryContainer: Color(0xFF4A1500),
    tertiary:             Color(0xFF1565C0),
    onTertiary:           Color(0xFFFFFFFF),
    tertiaryContainer:    Color(0xFFD2E4FF),
    onTertiaryContainer:  Color(0xFF001C47),
    error:                Color(0xFFBA1A1A),
    onError:              Color(0xFFFFFFFF),
    errorContainer:       Color(0xFFFFDAD6),
    onErrorContainer:     Color(0xFF410002),
    surface:              Color(0xFFFFFFFF),
    onSurface:            Color(0xFF001F1B),
    surfaceContainerHighest: Color(0xFFD9E5E2),
    onSurfaceVariant:     Color(0xFF3E4945),
    outline:              Color(0xFF6E7975),
    outlineVariant:       Color(0xFFBDC9C5),
    shadow:               Color(0xFF000000),
    scrim:                Color(0xFF000000),
    inverseSurface:       Color(0xFF2B3431),
    onInverseSurface:     Color(0xFFECF2F0),
    inversePrimary:       Color(0xFF7CD7CB),
  );

  static const ColorScheme australianClinicalDark = ColorScheme(
    brightness:           Brightness.dark,
    primary:              Color(0xFF7CD7CB),
    onPrimary:            Color(0xFF00372F),
    primaryContainer:     Color(0xFF005047),
    onPrimaryContainer:   Color(0xFFCCECE7),
    secondary:            Color(0xFFFFB59C),
    onSecondary:          Color(0xFF5C1600),
    secondaryContainer:   Color(0xFF852200),
    onSecondaryContainer: Color(0xFFFFCCBC),
    tertiary:             Color(0xFFADC8FF),
    onTertiary:           Color(0xFF003177),
    tertiaryContainer:    Color(0xFF0048A5),
    onTertiaryContainer:  Color(0xFFD2E4FF),
    error:                Color(0xFFFFB4AB),
    onError:              Color(0xFF690005),
    errorContainer:       Color(0xFF93000A),
    onErrorContainer:     Color(0xFFFFDAD6),
    surface:              Color(0xFF0E1513),
    onSurface:            Color(0xFFDCE4E1),
    surfaceContainerHighest: Color(0xFF3E4945),
    onSurfaceVariant:     Color(0xFFBDC9C5),
    outline:              Color(0xFF87938F),
    outlineVariant:       Color(0xFF3E4945),
    shadow:               Color(0xFF000000),
    scrim:                Color(0xFF000000),
    inverseSurface:       Color(0xFFDCE4E1),
    onInverseSurface:     Color(0xFF2B3431),
    inversePrimary:       Color(0xFF00695C),
  );

  // ── Lookup helpers ─────────────────────────────────────────────────────────

  static ColorScheme lightScheme(AppThemeVariant v) => switch (v) {
    AppThemeVariant.healthcareClassic   => healthcareClassicLight,
    AppThemeVariant.modernBlue          => modernBlueLight,
    AppThemeVariant.wellnessGreen       => wellnessGreenLight,
    AppThemeVariant.professionalDark    => professionalDark,
    AppThemeVariant.accessibility       => accessibilityLight,
    AppThemeVariant.australianClinical  => australianClinicalLight,
  };

  static ColorScheme darkScheme(AppThemeVariant v) => switch (v) {
    AppThemeVariant.healthcareClassic   => healthcareClassicDark,
    AppThemeVariant.modernBlue          => modernBlueDark,
    AppThemeVariant.wellnessGreen       => wellnessGreenDark,
    AppThemeVariant.professionalDark    => professionalDark,
    AppThemeVariant.accessibility       => accessibilityDark,
    AppThemeVariant.australianClinical  => australianClinicalDark,
  };

  // ── Per-theme Healthcare overrides ─────────────────────────────────────────

  /// Colors that differ between themes for healthcare-specific roles.
  static ({
    Color aiAccent, Color aiContainer, Color onAiContainer,
    Color prescription, Color labReport, Color radiology, Color discharge,
  }) healthcareOverrides(AppThemeVariant v) => switch (v) {
    AppThemeVariant.healthcareClassic => (
      aiAccent: const Color(0xFFF59E0B),
      aiContainer: const Color(0xFFFFF8E1),
      onAiContainer: const Color(0xFF3E2800),
      prescription: const Color(0xFF1565C0),
      labReport:    const Color(0xFF6A1B9A),
      radiology:    const Color(0xFF0277BD),
      discharge:    const Color(0xFF2E7D32),
    ),
    AppThemeVariant.modernBlue => (
      aiAccent: const Color(0xFF1855BF),
      aiContainer: const Color(0xFFDAE2FF),
      onAiContainer: const Color(0xFF001452),
      prescription: const Color(0xFF283593),
      labReport:    const Color(0xFF4A148C),
      radiology:    const Color(0xFF01579B),
      discharge:    const Color(0xFF1B5E20),
    ),
    AppThemeVariant.wellnessGreen => (
      aiAccent: const Color(0xFF2E6B33),
      aiContainer: const Color(0xFFB2EBB7),
      onAiContainer: const Color(0xFF002109),
      prescription: const Color(0xFF1A237E),
      labReport:    const Color(0xFF558B2F),
      radiology:    const Color(0xFF00696B),
      discharge:    const Color(0xFF1B5E20),
    ),
    AppThemeVariant.professionalDark => (
      aiAccent: const Color(0xFFFFCA28),
      aiContainer: const Color(0xFF1A1400),
      onAiContainer: const Color(0xFFFFCA28),
      prescription: const Color(0xFF82B1FF),
      labReport:    const Color(0xFFCE93D8),
      radiology:    const Color(0xFF4FC3F7),
      discharge:    const Color(0xFF69F0AE),
    ),
    AppThemeVariant.accessibility => (
      aiAccent: const Color(0xFF994400),
      aiContainer: const Color(0xFFFFF3CC),
      onAiContainer: const Color(0xFF3E1A00),
      prescription: const Color(0xFF0000CC),
      labReport:    const Color(0xFF4A0080),
      radiology:    const Color(0xFF003399),
      discharge:    const Color(0xFF006600),
    ),
    AppThemeVariant.australianClinical => (
      aiAccent: const Color(0xFFE65100),
      aiContainer: const Color(0xFFFFCCBC),
      onAiContainer: const Color(0xFF4A1500),
      prescription: const Color(0xFF1565C0),
      labReport:    const Color(0xFF6A1B9A),
      radiology:    const Color(0xFF0277BD),
      discharge:    const Color(0xFF2E7D32),
    ),
  };
}
